load("//tools:defaults.bzl", "ng_module")

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "will",
    srcs = [
        "will.ts",
    ],
    deps = [
        "@npm//@angular/compiler",
    ],
)
